services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: satellites_server
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./recordings:/recordings

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: satellites_frontend
    ports:
      - "5173:80"

  static:
    image: nginx
    container_name: satellites_static
    ports:
      - "8083:80"
    volumes:
      - ./recordings:/usr/share/nginx/html/recordings:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
